#!/usr/bin/env bash

if [ $# -lt 3 ]; then
    echo "Usage: $0 [awk opts...] <match idx> <match str> <print idx>" >&2
    exit 1
fi

match_idx="${@: -3:1}"
match_str="${@: -2:1}"
print_idx="${@: -1:1}"
set -- "${@:1:(($#-3))}"

awk "$@" "\$$match_idx == \"$match_str\" { print \$$print_idx }"
